name: Production

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.4
      with:
        node-version: 14.x

    - name: install dependencies
      run: yarn

    - name: Check lint
      run: yarn lint

    - name: Check tests  
      run: yarn test --bail

    - name: Run build
      run: yarn build
      env:
        REACT_APP_SERVER: ${{ secrets.REACT_APP_SERVER }}
        REACT_APP_OPMS: ${{ secrets.REACT_APP_OPMS }}
        REACT_APP_GA_TRACKING: ${{ secrets.REACT_APP_GA_TRACKING }}

    - name: Copy project to AGF
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: ${{ secrets.SSH_PORT }}
        password: ${{ secrets.SSH_PASS }}
        source: ".,!node_modules"
        target: "~/app/agf-dash"

    - name: Run production scripts
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: ${{ secrets.SSH_PORT }}
        password: ${{ secrets.SSH_PASS }}
        script: |
          cd ~/app/agf-dash
          pm2 restart agf-dash
