name: Validate PR

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.4
      with:
        node-version: 14.x

    - name: install dependencies
      run: yarn

    - name: Check lint
      run: yarn lint

    - name: Check tests
      run: yarn test --bail

    - name: Run build
      run: yarn build
      env:
        REACT_APP_SERVER: ${{ secrets.REACT_APP_SERVER }}
        REACT_APP_OPMS: ${{ secrets.REACT_APP_OPMS }}
